
CREATE TABLE FARMING (
	id INTEGER NOT NULL,
	name TEXT(50),
	"type" TEXT(50),
	start_date INTEGER,
	end_date INTEGER,
	fk_field INTEGER,
	CONSTRAINT FARMING_PK PRIMARY KEY (id),
	CONSTRAINT FARMING_FK FOREIGN KEY (fk_field) REFERENCES FIELD(id)
);

CREATE TABLE FIELD (
	id INTEGER NOT NULL,
	name TEXT(50),
	city TEXT(50),
	adress TEXT(150),
	surface_km2 INTEGER,
	surface_ha INTEGER,
	fk_farming INTEGER,
	CONSTRAINT FIELD_PK PRIMARY KEY (id),
	CONSTRAINT FIELD_FK FOREIGN KEY (fk_farming) REFERENCES FARMING(id)
);

CREATE TABLE ANIMAL (
	id INTEGER NOT NULL,
	name TEXT(50),
	"type" TEXT(50),
	"full" INTEGER NOT NULL,
	fk_animal_father INTEGER,
	fk_animal_mother INTEGER,
	fk_field INTEGER,
	CONSTRAINT ANIMAL_PK PRIMARY KEY (id),
	CONSTRAINT ANIMAL_FK FOREIGN KEY (fk_animal_father) REFERENCES ANIMAL(id),
	CONSTRAINT ANIMAL_FK_1 FOREIGN KEY (fk_animal_mother) REFERENCES ANIMAL(id),
	CONSTRAINT ANIMAL_FK_FIELD FOREIGN KEY (fk_field) REFERENCES FIELD(id)
);

CREATE TABLE INSEMINATION (
	id INTEGER NOT NULL,
	date INTEGER,
	bull_id TEXT(50),
	fk_animal_cow INTEGER,
	CONSTRAINT INSEMINATION_PK PRIMARY KEY (id),
	CONSTRAINT INSEMINATION_FK FOREIGN KEY (fk_animal_cow) REFERENCES ANIMAL(id)
);

CREATE TABLE TREATMENT (
	id INTEGER NOT NULL,
	name TEXT(50),
	"type" TEXT(50),
	start_date INTEGER,
	end_date INTEGER,
	fk_animal INTEGER,
	CONSTRAINT TREATMENT_PK PRIMARY KEY (id),
	CONSTRAINT TREATMENT_FK FOREIGN KEY (fk_animal) REFERENCES ANIMAL(id)
);
